require_relative './active_record_lite/04_associatable'
require_relative './active_record_lite/db_connection'
require_relative './active_record_lite/01_mass_object'
require_relative './active_record_lite/03_searchable'
require_relative './active_record_lite/02_sql_object'
